### ISSUE TITLE
.rdupe command crashes

### ISSUE THREAD

**Issue by GradientGamer-XD** [anOtherAnalyse/FamilyFunPack#42]
i logged on 9b9t and i typed .rdupe next to a lama and it crahses

LOG

---- Minecraft Crash Report ----

WARNING: coremods are present:
  KAMIBlueMixinLoader (kamiblue-2.04.21-3c581c22b.jar)
Contact their authors BEFORE contacting forge

// You should try our sister game, Minceraft!

Time: 10/31/22 3:59 PM
Description: Updating screen events

java.lang.NullPointerException: Updating screen events
	at family_fun_pack.modules.CommandsModule.handleCommand(CommandsModule.java:77)
	at family_fun_pack.modules.CommandsModule.onChat(CommandsModule.java:64)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_14_CommandsModule_onChat_ClientChatEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.event.ForgeEventFactory.onClientSendMessage(ForgeEventFactory.java:436)
	at net.minecraft.client.gui.GuiScreen.func_175281_b(GuiScreen.java:416)
	at net.minecraft.client.gui.GuiScreen.func_175275_f(GuiScreen.java:411)
	at net.optifine.gui.GuiChatOF.func_175275_f(GuiChatOF.java:41)
	at net.minecraft.client.gui.GuiChat.func_73869_a(SourceFile:81)
	at net.minecraft.client.gui.GuiScreen.func_146282_l(GuiScreen.java:558)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:512)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1759)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at family_fun_pack.modules.CommandsModule.handleCommand(CommandsModule.java:77)
	at family_fun_pack.modules.CommandsModule.onChat(CommandsModule.java:64)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_14_CommandsModule_onChat_ClientChatEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.event.ForgeEventFactory.onClientSendMessage(ForgeEventFactory.java:436)
	at net.minecraft.client.gui.GuiScreen.func_175281_b(GuiScreen.java:416)
	at net.minecraft.client.gui.GuiScreen.func_175275_f(GuiScreen.java:411)
	at net.optifine.gui.GuiChatOF.func_175275_f(GuiChatOF.java:41)
	at net.minecraft.client.gui.GuiChat.func_73869_a(SourceFile:81)
	at net.minecraft.client.gui.GuiScreen.func_146282_l(GuiScreen.java:558)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:512)

-- Affected screen --
Details:
	Screen name: net.optifine.gui.GuiChatOF

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['GradientGamer'/24562, l='MpServer', x=-46371.32, y=72.90, z=545.45]]
	Chunk stats: MultiplayerChunkCache: 49, 49
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (72,64,8), Chunk: (at 8,4,8 in 4,0; contains blocks 64,0,0 to 79,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 172797 game time, 1818904470 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 19 total; [EntitySquid['Squid'/5060717, l='MpServer', x=-46390.29, y=49.93, z=542.43], EntityPlayerSP['GradientGamer'/24562, l='MpServer', x=-46371.32, y=72.90, z=545.45], EntitySquid['Squid'/5060719, l='MpServer', x=-46393.04, y=47.30, z=530.71], EntitySquid['Squid'/5060718, l='MpServer', x=-46390.72, y=47.87, z=540.09], EntityXPOrb['Experience Orb'/5051273, l='MpServer', x=-46344.07, y=48.00, z=577.45], EntitySquid['Squid'/5051268, l='MpServer', x=-46395.23, y=54.48, z=525.30], EntitySquid['Squid'/5051271, l='MpServer', x=-46381.40, y=53.25, z=538.02], EntitySquid['Squid'/5051270, l='MpServer', x=-46391.94, y=50.32, z=534.19], EntitySquid['Squid'/5051265, l='MpServer', x=-46398.94, y=58.99, z=563.39], EntitySquid['Squid'/5051260, l='MpServer', x=-46396.50, y=61.51, z=543.99], EntitySquid['Squid'/5059199, l='MpServer', x=-46397.79, y=56.35, z=563.46], EntitySquid['Squid'/5051259, l='MpServer', x=-46403.38, y=57.33, z=541.91], EntityBoat['Boat'/5051249, l='MpServer', x=-46374.19, y=62.52, z=559.69], EntitySquid['Squid'/5060721, l='MpServer', x=-46395.00, y=48.72, z=536.76], EntitySquid['Squid'/5060720, l='MpServer', x=-46389.94, y=49.34, z=530.00], EntityLlama['Llama'/5051251, l='MpServer', x=-46370.45, y=72.00, z=544.45], EntitySquid['Squid'/5060723, l='MpServer', x=-46394.81, y=48.18, z=530.28], EntityLlama['Llama'/5051250, l='MpServer', x=-46371.02, y=72.00, z=545.47], EntitySquid['Squid'/5060722, l='MpServer', x=-46393.35, y=49.94, z=531.70]]
	Retry entities: 0 total; []
	Server brand: Waterfall <- Paper
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 725550168 bytes (691 MB) / 1140850688 bytes (1088 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 Optifine OptiFine_1.12.2_HD_U_G5 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID              | Version           | Source                         | Signature                                |
	|:------ |:--------------- |:----------------- |:------------------------------ |:---------------------------------------- |
	| LCHIJA | minecraft       | 1.12.2            | minecraft.jar                  | None                                     |
	| LCHIJA | mcp             | 9.42              | minecraft.jar                  | None                                     |
	| LCHIJA | FML             | 8.0.99.99         | forge-1.12.2-14.23.5.2854.jar  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge           | 14.23.5.2854      | forge-1.12.2-14.23.5.2854.jar  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | family_fun_pack | 1.1.5             | family_fun_pack-1.1.5.jar      | None                                     |
	| LCHIJA | kamiblue        | 2.04.21-3c581c22b | kamiblue-2.04.21-3c581c22b.jar | None                                     |

	Loaded coremods (and transformers): 
KAMIBlueMixinLoader (kamiblue-2.04.21-3c581c22b.jar)
  
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.13558 Compatibility Profile Context 26.20.11008.6001' Renderer: 'AMD Radeon(TM) Vega 8 Graphics'
	Launched Version: 1.12.2-forge-14.23.5.2854
	LWJGL: 2.9.4
	OpenGL: AMD Radeon(TM) Vega 8 Graphics GL version 4.6.13558 Compatibility Profile Context 26.20.11008.6001, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: vanilla, file/GradientFPS (incompatible), file/Named (incompatible), programer_art, Fabric Mods
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x AMD Ryzen 5 2500U with Radeon Vega Mobile Gfx 
	OptiFine Version: OptiFine_1.12.2_HD_U_G5
	OptiFine Build: 20210124-142939
	Render Distance Chunks: 7
	Mipmaps: 1
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.13558 Compatibility Profile Context 26.20.11008.6001
	OpenGlRenderer: AMD Radeon(TM) Vega 8 Graphics
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 8

**Comment by GradientGamer-XD** [comment]
Mods Used

KamiBlue - Latest
FFP - latest
OptiFine 1.12 - latest

**Comment by anOtherAnalyse** [comment]
Thanks for reporting, I will fix this. You can use version 1.1.4 while I do that.

**Comment by bstar16** [comment]
most commands produce the same crash btw

**Comment by anOtherAnalyse** [comment]
Indeed. Fixed.
